# Generated by Django 3.0.4 on 2021-06-03 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baby.Type'),
        ),
    ]
